name: coin_flipper
description: A simple Flutter Web coin flipper app.
publish_to: 'none' # not published to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.10
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

