// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjUKIT6uhSLVhW4g_t7tS4tNBewZVsfbY',
    appId: '1:268859924374:web:73b63991f186bf7d81c7b7',
    messagingSenderId: '268859924374',
    projectId: 'coinflipper-13eaa',
    authDomain: 'coinflipper-13eaa.firebaseapp.com',
    storageBucket: 'coinflipper-13eaa.firebasestorage.app',
    measurementId: 'G-6Q919E7M84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_i6fwFjqNNGXz6OBGWzdgjP8Pb5U0lDY',
    appId: '1:268859924374:android:5ef43c65e5ea367f81c7b7',
    messagingSenderId: '268859924374',
    projectId: 'coinflipper-13eaa',
    storageBucket: 'coinflipper-13eaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpfW8LWU4_iIWQAoh79tyS2pZmZp6nht4',
    appId: '1:268859924374:ios:89f1e85d499c4fb981c7b7',
    messagingSenderId: '268859924374',
    projectId: 'coinflipper-13eaa',
    storageBucket: 'coinflipper-13eaa.firebasestorage.app',
    iosBundleId: 'com.example.coinFlipper',
  );
}
